baseurl = "/"
title = "Myšlenky dne otce Fura"
languageCode = "cs-cz"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Jan Novotný"
    bio = "Alias Novoj. Vývojář v FG Forrest, autor Kafemlejnek.TV, spoluorganizátor jOpenSpace ne-konference."
    avatar = "img/avatar.png"


[Params]
    subtitle = "Dává je jen zřídka, obvykle jim není moc rozumět a často vám ani k ničemu nejsou." # Subtitle of your site
    description = "Profesní blog." # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["posts"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)